### ISSUE TITLE
 lolin32_lite

### ISSUE THREAD

**Issue by winner69** [tadelv/almost-decent-scale#2]
I'm a beginner and I want to use the WEMOS LOLIN32 Lite board. Can you give me some advice? I've been trying to use the platformio.ini file all day and it keeps giving me the following error:

[env]
platform = espressif32
test_framework = googletest

[env:native]
platform = native
lib_deps = 
	HX711
	h2zero/NimBLE-Arduino@^1.4.1

[scale-core]
framework = arduino
; board = esp32-s3-devkitm-1
lib_deps = 
	HX711
	h2zero/NimBLE-Arduino@^1.4.1
build_flags =
  -std=c++2a
  ; -D LV_CONF_PATH="${PROJECT_DIR}/include/lv_conf.h"

[env:elolin32_lite]
extends = scale-core
board = lolin32_lite
monitor_speed = 115200
build_flags = 
  ${scale-core.build_flags}
  -D LOADCELL_DOUT_PIN=17
  -D LOADCELL_SCK_PIN=18

[env:esp32-s3-mini]
extends = scale-core
board = lolin_s3_mini
monitor_speed = 115200
monitor_filters = send_on_enter
monitor_eol = LF
build_flags = 
  ${scale-core.build_flags}
  -DARDUINO_USB_CDC_ON_BOOT
  -DBOARD_HAS_PSRAM
  -DCORE_DEBUG_LEVEL=3
  -D LOADCELL_DOUT_PIN=8
  -D LOADCELL_SCK_PIN=6
  -D BT_COMMS_NIMBLE
  -D DEBUG_SERIAL=Serial
  -D LOGSerial=Serial

show error 
Environment    Status    Duration
-------------  --------  ------------
native         FAILED    00:00:00.701
elolin32_lite  FAILED    00:00:05.565
esp32-s3-mini  SUCCESS   00:00:25.366

src/main.cpp:15:3: error: 'LOGSerial' was not declared in this scope
src/main.cpp:25:3: error: 'LOGSerial' was not declared in this scope
src/main.cpp:48:7: error: 'LOGSerial' was not declared in this scope
*** [.pio\build\elolin32_lite\src\main.cpp.o] Error 1

**Comment by tadelv** [comment]
Hey, you're missing the defines for DEBUG_SERIAL and LOGSerial! Add this to platformio.ini:

```
[env:elolin32_lite]
extends = scale-core
board = lolin32_lite
monitor_speed = 115200
build_flags =
${scale-core.build_flags}
-D LOADCELL_DOUT_PIN=17
-D LOADCELL_SCK_PIN=18
-D BT_COMMS_NIMBLE
-D DEBUG_SERIAL=Serial
-D LOGSerial=Serial
```

**Comment by winner69** [comment]
The code successfully flashes onto the ESP32 and can connect to the app, 
but it can't send any data to the application (specifically weight). I've already tested the load cell and it works with other code.

**Comment by tadelv** [comment]
Ok, one step closer.

I assume when you say there’s no data, it’s sending gibberish? Or is it
zeros?

If you’re getting zero weight all the time, it might also be a wiring
issue.


I would suggest, that you calibrate the scale again. Either follow the
approach described in readme, via bluetooth, or have the scale connected to
the computer and use the serial monitor in platformio to send ‘c’ to start
calibration, have a known weight ready and then when it tells you the units
number, press ‘f’ to enter and store the factor.

Hope this helps

**Comment by winner69** [comment]
Thank you, I'll try :)
